package com.cobosideas.lista.activities.MainActivity.room.DAO;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;
import com.cobosideas.lista.activities.MainActivity.room.models.ItemRoom;

import java.util.List;

@Dao
public interface ItemDAO {
    @Insert
    Long insert(ItemRoom items);//return the Long value from autoGenerated
    @Update
    void update(ItemRoom items);
    @Delete
    void delete(ItemRoom items);

    @Query("SELECT * FROM items WHERE id = :id")
    ItemRoom getItemById(Long id);

    @Query("SELECT * FROM items")
    List<ItemRoom> getItems();
}
