package com.cobosideas.lista.activities.lists;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;

@Dao
public interface DAOItemLists {
    @Insert
    Long insert(ModelItemLists itemLists); //return the Long value from autoGenerated
    @Update
    void update(ModelItemLists itemLists);
    @Delete
    void delete(ModelItemLists itemLists);

    @Query("SELECT * FROM itemLists WHERE id = :id")
    ModelItemLists getItemListsById(Long id);

    @Query("SELECT * FROM itemLists")
    List<ModelItemLists> getAllItemsLists();
}
