package com.cobosideas.lista.activities.manage_functions;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;
@Dao
public interface DAOItemFunctions {
    @Insert
    Long insert(ModelItemManageFunctions itemManageFunctions); //return the Long value from autoGenerated
    @Update
    void update(ModelItemManageFunctions itemManageFunctions);
    @Delete
    void delete(ModelItemManageFunctions itemManageFunctions);

    @Query("SELECT * FROM itemManageFunctions WHERE id = :id")
    ModelItemManageFunctions getItemListsById(Long id);

    @Query("SELECT * FROM itemManageFunctions")
    List<ModelItemManageFunctions> getAllItemsLists();
}
